name: Test Artifact
on: workflow_dispatch
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
         name: file
     - name: Check file
       run: ls
